name: 'Bolt by Koalalab'
description: 'Bolt - Transparnt egress gateway for build environments'
author: 'Koalalab-inc'
branding:
  color: 'black'
  icon: 'zap'
# Define your inputs here.
inputs:
  mode:
    description: 'Mode of operation - audit or block'
    required: false
    default: 'audit'
  allow_http:
    description: 'Allow HTTP traffic'
    required: false
    default: false
  default_policy:  
    description: 'Default policy for egress traffic - allow-all or block-all'
    required: false
    default: 'block-all'
  trusted_github_accounts:
    description: 'Trusted Github accounts'
    required: false
    default: '[]'
  egress_rules:
    description: 'Egress rules'
    required: false
    default: '[]'

# Define your outputs here.
outputs:
  egress_report:
    description: 'Egress report'

runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
