name: 'Bolt'
description: 'Bolt - Transparnt egress gateway for build environments'
author: 'Koalalab-inc'

# Define your inputs here.
inputs:
  mode:
    description: 'Mode of operation - audit or block'
    required: false
    default: 'audit'
  allow_http:
    description: 'Allow HTTP traffic'
    required: false
    default: false
  default_policy:  
    description: 'Default policy for egress traffic - allow-all or block-all'
    required: false
    default: 'block-all'
  egress_rules:
    description: 'Egress rules'
    required: false
    default: |
      - name: 'Allow ifconfig.me'
        action: 'allow'
        domain: 'ifconfig.me'

# Define your outputs here.
outputs:
  egress_report:
    description: 'Egress report'

runs:
  using: node20
  main: dist/index.js
