name: release

on:
  push:
    tags:
      - v*.*.*

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      tag: ${{ github.ref_name }}
      os: linux
      arch: x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get release version
        id: releaseVersion
        run: echo "releaseVersion=\"$(awk -F\' '/export const releaseVersion/ { print $2 }' src/version.js)\"" >> "$GITHUB_ENV"
      - name: Check if releaseVersion is same as tag
        run: |
          if [ "${{ env.tag }}" != "${{ env.releaseVersion }}" ]; then
            echo "releaseVersion does not match the tag"
            exit 1
          fi
      - name: Fetch MITM-Proxy
        run: |
          mkdir -p mitmproxy
          wget https://downloads.mitmproxy.org/10.2.2/mitmproxy-10.2.2-${{ env.os }}-${{ env.arch }}.tar.gz --quiet
          tar -xzf mitmproxy-10.2.2-${{ env.os }}-${{ env.arch }}.tar.gz -C mitmproxy
          mkdir -p bolt
          cp mitmproxy/mitmdump bolt/mitmdump
          cp src/intercept.py bolt/intercept.py
          tar -czf bolt-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz bolt
          rm -rf mitmproxy bolt
          rm mitmproxy-10.2.2-linux-x86_64.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: bolt-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz
          tag_name: ${{ env.tag }}
          name: ${{ env.tag }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ endsWith(env.tag, 'rc') }}
